version: '3.8'

services:
  nextcloud:
    build: .
    container_name: nextcloud
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_PASSWORD: nextcloudpass
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: adminpass
      PHP_MEMORY_LIMIT: 512M 
    volumes:
      - nextcloud_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini

volumes:
  nextcloud_data:
