version: '3.8'

services:
  nextcloud:
    build: .
    container_name: nextcloud
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_PASSWORD: nextcloudpass
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: adminpass
    volumes:
      - nextcloud_data:/var/www/html

      
volumes:
  nextcloud_data:
